name: Validate

on:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the main repository (where workflow runs)
      - name: Checkout main repository
        uses: actions/checkout@v4

      # Step 3: Use the composite action
      - name: Run Composite Action
        uses: aparnajyothi-y/testcomposite@main
